### ISSUE TITLE
Запис слів у файл при використанні Python 2.7

### ISSUE THREAD

**Issue by anrom7** [anrom7/CL_Project#8]
У гілку Romanyuk(examples) додано програмку яка коректно записує слова у файл при використанні Python 2.7

**Comment by Rurych-Ivanna** [comment]
Дякуємо!)

понеділок, 6 квітня 2015 р. користувач anrom7 notifications@github.com
написав:

**Comment by Rurych-Ivanna** [comment]
вибиває о таку помилку:
Traceback (most recent call last):
  File "C:\CL_Project\find_550_words_27.py", line 13, in <module>
    stopwords=PlaintextCorpusReader(stopwords_path, 'ukrainian1', encoding='utf-8').words()
  File "C:\Python27\lib\site-packages\nltk\corpus\reader\plaintext.py", line 61, in **init**
    CorpusReader.**init**(self, root, fileids, encoding)
  File "C:\Python27\lib\site-packages\nltk\corpus\reader\api.py", line 78, in **init**
    root = FileSystemPathPointer(root)
  File "C:\Python27\lib\site-packages\nltk\data.py", line 154, in **init**
    raise IOError('No such file or directory: %r' % path)
IOError: No such file or directory: 'C:\Python27\nltk_data\corpora\stopwords'

в чому причина, файл ukrainian1 знаходиться за шляхом: C:\Python27\nltk_data\corpora\stopwords??

**Comment by anrom7** [comment]
покладіть ukrainian1 туди де лежить find_550_words_27.py
